/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_victor_androiddemos_util_HelloJni */

#ifndef _Included_pers_victor_androiddemos_util_HelloJni
#define _Included_pers_victor_androiddemos_util_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_victor_androiddemos_util_HelloJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_victor_androiddemos_util_HelloJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
